# Docs: https://circleci.com/docs/2.0/language-javascript/
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test_and_release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run linter
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Run tests
          command: yarn test --watchAll=false --ci --coverage --reporters=default --reporters=jest-junit --runInBand
      - codecov/upload:
          file: coverage/*.json
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Compile the code
          command: yarn compile
      - run:
          name: Release
          command: yarn release

  deploy-web:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build website
          command: yarn build
      # This is necessary to avoid the error related to permissions of Github (see official docs)
      - add_ssh_keys:
          fingerprints:
            - 'd3:31:7b:2f:30:65:1a:a7:43:aa:4a:af:7c:74:87:0e'
      - run:
          name: Deploy website
          command: yarn deploy-web

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_and_release
      - deploy-web:
          requires:
            - test_and_release
            # The release process updates the version of package.json so it needs to be synchronous 
            - release
          filters:
            branches:
              only: master
